runtime: nodejs20

instance_class: F4

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  SESSION_SECRET: "${SESSION_SECRET}"
  DATABASE_URL: "${DATABASE_URL}"
  PGDATABASE: "${PGDATABASE}"
  PGHOST: "${PGHOST}"
  PGPORT: "5432"
  PGUSER: "${PGUSER}"
  PGPASSWORD: "${PGPASSWORD}"
  SMTP_PORT: "587"
  SMTP_USER: "${SMTP_USER}"
  M365_CLIENT_ID: "${M365_CLIENT_ID}"
  M365_CLIENT_SECRET: "${M365_CLIENT_SECRET}"
  CUSTOM_DOMAIN: "pivotal-b2b.com"

# IMPORTANT: SMTP_HOST/SMTP_PASSWORD remain to be provided via Secret Manager or env overrides before prod email

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
