runtime: nodejs20

instance_class: F4

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  SESSION_SECRET: "your-session-secret-here"
  DATABASE_URL: "your-database-url-here"
  PGDATABASE: "your-database-name"
  PGHOST: "your-database-host"
  PGPORT: "5432"
  PGUSER: "your-database-user"
  PGPASSWORD: "your-database-password"
  SMTP_PORT: "587"
  SMTP_USER: "your-smtp-user"
  M365_CLIENT_ID: "your-m365-client-id"
  M365_CLIENT_SECRET: "your-m365-client-secret"
  CUSTOM_DOMAIN: "your-domain.com"

# IMPORTANT: Replace placeholder values above with actual secrets before deploying
# For production, use Google Cloud Secret Manager for sensitive values

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Skip files that shouldn't be uploaded
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.ts$
  - ^(.*/)?.*\.tsx$
  - node_modules/
  - client/src/
  - server/
  - scripts/
  - .git/
  - .gitignore
  - README.md
  - tsconfig.json
  - vite.config.ts
  - tailwind.config.ts
  - postcss.config.js
  - drizzle.config.ts
