# Cloud Build Configuration for Google Cloud Run
# This file defines the build and deployment pipeline for containerized deployment

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/corporate-website:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/corporate-website:latest',
      '.'
    ]
    id: 'build-image'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/corporate-website:$COMMIT_SHA']
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/corporate-website:latest']
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'corporate-website'
      - '--image=gcr.io/$PROJECT_ID/corporate-website:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--port=8080'
    id: 'deploy-cloudrun'
    waitFor: ['push-image-sha']

# Docker images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/corporate-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/corporate-website:latest'

# Timeout for the entire build
timeout: '1800s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'
